/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dao.RouteDao;
import dao.impl.RouteDaoImpl;
import java.util.List;
import model.Route;

/**
 *
 * @author Gustavo Ramos
 */
public class frmListRoutes extends javax.swing.JInternalFrame {

    List<Route> listRoutes;

    /**
     * Creates new form frmListRoutes
     */
    public frmListRoutes() {
        initComponents();
        RouteDao rdao = new RouteDaoImpl();
        listRoutes = rdao.getAll();
        String oo[][] = new String[listRoutes.size()][3];
        for (int i = 0; i < listRoutes.size(); i++) {
            Route r = (Route) listRoutes.get(i);
            oo[i][0] = "" + r.getId();
            oo[i][1] = r.getOrigin();
            oo[i][2] = r.getDestiny();
        }
        gridRoutes.setModel(new javax.swing.table.DefaultTableModel(
                oo,
                new String[]{
                    "Id", "Origen", "Destino"
                }
        ));
        jScrollPane1.setViewportView(gridRoutes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searcher = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridRoutes = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();

        setClosable(true);
        setTitle("Lista de Rutas");
        setToolTipText("");
        setVisible(true);

        jLabel1.setText("Buscar:");

        searcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcherActionPerformed(evt);
            }
        });
        searcher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searcherKeyReleased(evt);
            }
        });

        btnNew.setText("Nuevo");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        gridRoutes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridRoutes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridRoutesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridRoutes);

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searcher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNew))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void searcherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searcherKeyReleased
        RouteDao rdao = new RouteDaoImpl();
        listRoutes = rdao.getAllCoincidences(searcher.getText().trim());
        String oo[][] = new String[listRoutes.size()][3];
        for (int i = 0; i < listRoutes.size(); i++) {
            Route route = (Route) listRoutes.get(i);
            oo[i][0] = "" + route.getId();
            oo[i][1] = route.getOrigin();
            oo[i][2] = route.getDestiny();
        }
        gridRoutes.setModel(new javax.swing.table.DefaultTableModel(
                oo,
                new String[]{
                    "Id", "Origen", "Destino"
                }
        ));
        jScrollPane1.setViewportView(gridRoutes);
    }//GEN-LAST:event_searcherKeyReleased

    private void searcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searcherActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        new dlgRoute(new javax.swing.JFrame(), true, null).setVisible(true);
        searcherKeyReleased(null);
    }//GEN-LAST:event_btnNewActionPerformed

    private void gridRoutesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridRoutesMouseClicked

        new dlgRoute(new javax.swing.JFrame(), true, new Route(
                Integer.parseInt(gridRoutes.getValueAt(gridRoutes.getSelectedRow(), 0).toString()),
                gridRoutes.getValueAt(gridRoutes.getSelectedRow(), 1).toString(),
                gridRoutes.getValueAt(gridRoutes.getSelectedRow(), 2).toString()
        )).setVisible(true);
        searcherKeyReleased(null);
    }//GEN-LAST:event_gridRoutesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JTable gridRoutes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searcher;
    // End of variables declaration//GEN-END:variables
}
