/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import report.CReporte;

/**
 *
 * @author Gustavo Ramos
 */
public class MainMDI extends javax.swing.JFrame {

    /**
     * Creates new form MainMDI
     */
    public MainMDI() {
        initComponents();
        fileMenu.setVisible(Boolean.FALSE);
        editMenu.setVisible(Boolean.FALSE);
        helpMenu.setVisible(Boolean.FALSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        mnuMaintenance = new javax.swing.JMenu();
        mnuRouteMant = new javax.swing.JMenuItem();
        mnuAirportMant = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        mnusRoute = new javax.swing.JMenu();
        mnuiRouteAll = new javax.swing.JMenuItem();
        mnusAiport = new javax.swing.JMenu();
        mnuAirportAll = new javax.swing.JMenuItem();
        mnuAirportName = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación Viajero");
        setBackground(new java.awt.Color(0, 102, 102));
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        desktopPane.setToolTipText("");
        desktopPane.setName(""); // NOI18N

        menuBar.setToolTipText("Aplicacion Viajero");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        mnuMaintenance.setText("Mantenimiento");

        mnuRouteMant.setText("Ruta");
        mnuRouteMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRouteMantActionPerformed(evt);
            }
        });
        mnuMaintenance.add(mnuRouteMant);

        mnuAirportMant.setText("Aeropuerto");
        mnuAirportMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAirportMantActionPerformed(evt);
            }
        });
        mnuMaintenance.add(mnuAirportMant);

        menuBar.add(mnuMaintenance);

        mnuReports.setText("Reportes");

        mnusRoute.setText("Ruta");

        mnuiRouteAll.setText("Lista Completa");
        mnuiRouteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiRouteAllActionPerformed(evt);
            }
        });
        mnusRoute.add(mnuiRouteAll);

        mnuReports.add(mnusRoute);

        mnusAiport.setText("Aeropuerto");

        mnuAirportAll.setText("Lista Completa");
        mnuAirportAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAirportAllActionPerformed(evt);
            }
        });
        mnusAiport.add(mnuAirportAll);

        mnuAirportName.setText("Lista por Nombre");
        mnuAirportName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAirportNameActionPerformed(evt);
            }
        });
        mnusAiport.add(mnuAirportName);

        mnuReports.add(mnusAiport);

        menuBar.add(mnuReports);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        desktopPane.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnuRouteMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRouteMantActionPerformed
        frmListRoutes frm = new frmListRoutes();
        desktopPane.add(frm);
        frm.show();
    }//GEN-LAST:event_mnuRouteMantActionPerformed

    private void mnuAirportMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAirportMantActionPerformed
        frmListAirports frm = new frmListAirports();
        desktopPane.add(frm);
        frm.show();
    }//GEN-LAST:event_mnuAirportMantActionPerformed

    private void mnuiRouteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiRouteAllActionPerformed
        
        //new CReporte().listRoutes(); 
        new CReporte().listRoutes();
    }//GEN-LAST:event_mnuiRouteAllActionPerformed

    private void mnuAirportAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAirportAllActionPerformed
        new CReporte().listAirports();
    }//GEN-LAST:event_mnuAirportAllActionPerformed

    private void mnuAirportNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAirportNameActionPerformed
        new dlgAirportPName(new javax.swing.JFrame(), true).setVisible(true);
    }//GEN-LAST:event_mnuAirportNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAirportAll;
    private javax.swing.JMenuItem mnuAirportMant;
    private javax.swing.JMenuItem mnuAirportName;
    private javax.swing.JMenu mnuMaintenance;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenuItem mnuRouteMant;
    private javax.swing.JMenuItem mnuiRouteAll;
    private javax.swing.JMenu mnusAiport;
    private javax.swing.JMenu mnusRoute;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
